version: "3.8"

#volumes:
#  app_media: {}

services:
  app:
    ports:
      - "48000:8000"
    command: /start.sh

    user: "${UID-1000}"
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/

    volumes:
      - ./media:/wd/media:rw
      # - app_media:/wd/media:rw

  postgres:
    ports:
      - "45432:5432"
