version: "3.8"

volumes:
  postgres_data: {}

services:
  app:
    build: .

    ports:
      - "8000:8000"

    user: "${UID-1000}"
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    volumes:
      - ./media:/wd/media:rw
      - ./static:/wd/static:rw

    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --workers 3 --bind 0.0.0.0:8000 django_csv_analysis.wsgi:application"

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.2-alpine3.19

    ports:
      - "45432:5432"

    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username ${POSTGRES_USER}  --dbname ${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

  nginx:
    image: nginx:latest

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./media:/wd/media:rw
      - ./static:/wd/static:ro

    depends_on:
      - app
